title: Ronaldo Setzer
email: ronaldo.setzer@gmail.com
description: > 
  Just a simple portfolio.
baseurl: "/portfolio"
url: "https://ronaldosetzer.github.io"
twitter_username: RonaldoSetzer
github_username:  RonaldoSetzer

# Build settings
markdown: kramdown
